@echo off
echo ======== START ========
echo Starting at %DATE% %TIME%...
echo Preprocessing...
gcc -E -x c src\pkp.pnml -o tmp\pkp-set.nml
echo Compiling...
nmlc -c --grf pkp-set-2.0.14.grf tmp\pkp-set.nml
echo Copying...
copy pkp-set-2.0.14.grf "C:\Users\tadeuszd\Documents\OpenTTD\content_download\newgrf"
echo ========= END =========